version: '1.0'
name: pipeline-20231102
displayName: subata_build
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - v-wiki
stages:
  - name: stage-b47955cb
    displayName: 打包任务
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install pnpm -g
          - ''
          - '# 安装依赖'
          - pnpm install
          - ''
          - '# 打包'
          - npm run docs:build
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./src/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
          timeout: 10
